---
- name: install apache2 and httpd
  hosts: webservers
  become: true
  gather_facts: yes
  tasks:
  - name : install httpd
    yum:
            name: httpd
            state: installed
    when: ansible_os_family == "RedHat"

  - name: start httpd
    service:
            name: httpd
            state: started
    when: ansible_os_family == "RedHat"

  - name: install apache2
    apt:
            update_cache: yes
            name: apache2
            state: present
    when: ansible_os_family == "Debian"

  - name: start apache2 service
    service:
            name: apache2
            state: started
    when: ansible_os_family == "Debian"   
