---
- name: install apache2 and httpd
  hosts: all
  become: true
  gather_facts: yes
  tasks:
  - name : install httpd
    yum:
            name: httpd
            state: installed
    when: ansible_os_family == "RedHat"

  - name: start httpd
    service:
            name: httpd
            state: started
    when: ansible_os_family == "RedHat"    
