---
- name: This playbook uninstall http and stop the service
  hosts: webservers
  become: true
  tasks:
  - name: stop httpd servide
    service:
            name: httpd
            state: stopped
  - name: uninstall packages
    yum:
            name: httpd
            state: removed 
